apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-demo
  name: argo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-demo
  template:
    metadata:
      labels:
        app: argo-demo
    spec:
      containers:
      - image: aytemur44/argolab:latest
        name: argo-demo
        resources:
         limits:
           memory: 400Mi
           cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: argo-demo
